4teamwork/ftw.keywordwidget

- docs/HISTORY.txt
- ftw/keywordwidget/widget.py
The makes sure that all terms from the request are in the vocabulary.
This works well until you enter a term containing umlauts. 
The request contains a Unicode string an the vocabulary 7bit ascii string. 
The fallback results in a empty vocabulary, since the term in the request containing a umlaut is not in the vocabulary (only the 7bit ascii representation).
> BugFix regarding vocabularies and the tags feature of select2.

- docs/HISTORY.txt
- ftw/keywordwidget/profiles/select2js/cssregistry.xml
- ftw/keywordwidget/profiles/select2js/jsregistry.xml
The folder was renamed, but this was not updated in the profile's configuration.
Fix for the changes introduced in https://github.com/4teamwork/ftw.keywordwidget/pull/5.
> Fix selec2js profile path to select2 resources.

- docs/HISTORY.txt
- ftw/keywordwidget/testing.py
- ftw/keywordwidget/tests/behavior.py
- ftw/keywordwidget/tests/test_widget.py
- ftw/keywordwidget/tests/tests.zcml
- ftw/keywordwidget/widget.py
Currently when the widget is rendered with `select2js` it will drop user input in the add-form when other fields have validation errors. This PR fixes that issue by always marking user input as a `selected` option in the select field when rendering the form after it has been submitted once.
At the moment the choice field is initialized too late during the forms `update`. It won't be set during
the first call to `extract` which happens during super's update and should set the submitted value on the widget. Thus the value won't be saved on the widget correctly and won't be rendered as selected. This PR moves the choice-field initialization before the super call to make
sure that the choice_field is already available in the first call to `extract`.
The second call to `extract` will then …
> Don't drop user-input when a form including the widget has validation errors.

- docs/HISTORY.txt
- ftw/keywordwidget/tests/test_widget.py
- ftw/keywordwidget/widget.py
This PR fixes an issue with keywords that contain non-ascii characters being duplicated after encountering at least one validation error on the form they are created with.
Also it refactors and simplifies control flow of `extract` and introduces a helper function to generate the token for the vocabulary term.
Fixes #11.
Before this PR broken, tags with e.g. umlauts were duplicated when creating the content after encountering a validation error in the form before saving:
> Fix keywords with non-ascii character being duplicated after validation error

- README.rst
- docs/HISTORY.txt
- ftw/keywordwidget/behavior.py
- ftw/keywordwidget/configure.zcml
- ftw/keywordwidget/locales/de/LC_MESSAGES/ftw.keywordwidget.po
- ftw/keywordwidget/locales/ftw.keywordwidget.pot
- ftw/keywordwidget/search.py
- ftw/keywordwidget/templates/keyword.js.pt
- ftw/keywordwidget/templates/keyword_input.pt
- ftw/keywordwidget/tests/test_different_cases.py
- ftw/keywordwidget/vocabularies.py
- ftw/keywordwidget/widget.py
- This implementation depends on the `IQuerySource` of from `z3c.formwidget.query`
IQuerySource is a special implementation of ISource, which has a `search` method. The search method is required für a async search of the result.
- If `async=True` the ContextSourceBinder needs to return a IQuerySource, otherwise the widget cannot be rendered. 
- If `async=True` it's not possible to add new elements.
- The backend only loads the selected items by calling `getTerm` (aka getItemByValue), which should be fast.
-  The default options of `ajax` of select2 are:
```
{'url': 'url/to/search/endpoint',
'dataType': 'json',
'delay': 250}
```
> Implement async option.

- docs/HISTORY.txt
- ftw/keywordwidget/tests/__init__.py
- ftw/keywordwidget/tests/test_different_cases.py
- ftw/keywordwidget/tests/widget.py
- ftw/keywordwidget/widget.py
This makes it simpler to write tests with the Keywordwidget, which has async option active.
Issue:
There are no options available after rendering the form, since the possible options are collected asynchronous and inserted into the DOM by JS.
The widget implemented in this PR makes exactly the same but with lxml.
Implementation issue:
Since the markup is a regular select field it's not possible to let the testbrowser automatically fill the form using the right `PloneWidget`. In tests you need to use the implemented PloneWidget explicitly.
```python 
form = browser.find_form_by_field('async')
form.find_widget('async').fill(['foo', 'bar'])
form.submit()
```
This pr also fixes I regression as I wrote tests to make sure everything works as expected. The `updateTerms` method accidentally …
> Add testbrowser widget for Keywordwidgets with async option.

- docs/HISTORY.txt
- ftw/keywordwidget/widget.py
Check `z3c.form.widget.Widget.update`
> BugFix: Get stored terms by token not by value, since self.value stores the widget value.

- docs/HISTORY.txt
- ftw/keywordwidget/configure.zcml
This removes the following warning when starting up the instance:
`WARNING plone.behavior Specifying 'for' in behavior 'Test behavior for keywordwidget Use-Cases' if no 'factory' is given has no effect and is superfluous.`
See https://github.com/plone/plone.behavior/blob/master/plone/behavior/metaconfigure.py#L154-L156.
> Remove superfluous `for` attribute for a behavior without a `factory` configured.

- docs/HISTORY.txt
- ftw/keywordwidget/resources/js/keywordwidget.js
Before:
If you start typing a term and select a match, the typed term was also added to the select. 
After:
Get the new value from the select widget itself.
> BugFix: No longer add items if they're not "really" selected.

- docs/HISTORY.txt
- ftw/keywordwidget/resources/js/keywordwidget.js
If the single value field gets focused it automatically opens the menu (incl. the searchbox).
The prevents us from a additional click.
The reason for hackish implementation of the triggering the menu on focus is https://github.com/select2/select2/issues/1908
focus on select2 is currently not supported 😢 
And I stumbled over a bug while selecting a single item.
> Automatically open the menu on single value fields + BugFix

- docs/HISTORY.txt
- ftw/keywordwidget/resources/js/keywordwidget.js
The bug was introduced in 1.3.3, `select2.val()`  returns a list of strings not an object.
In 1.3.3 and 1.3.4 it was no longer possible to add new keywords.
> Fix adding new terms

- README.rst
- ftw/keywordwidget/resources/js/keywordwidget.js
- ftw/keywordwidget/templates/keyword_input.pt
- ftw/keywordwidget/widget.py
This PR add the possiblity to use own templates for the results or the selected items (https://select2.org/selections)
How does it work?
The Keywordwidget will trigger an event called `ftwKeywordWidgetInit` once after it has been initialized.
This is the place, where you need to hook in.
Register an event-listener for this event and register your own template:
```javascript
$(document).on('ftwKeywordWidgetInit', function(e) {
window.ftwKeywordWidget.registerTemplate('myPurpleTheme', function(data) {
return $('<span style="background-color:purple" />').text(data.text);
});
});
```
Now, the template is available for your widgets. Next you need to use your template in a widget:
```python
form.widget('reading', KeywordFieldWidget, template_selection='MyPurpleTheme')
```
Your widget will be …
> Add possiblity to add templates for the select2 widget.

- README.rst
- ftw/keywordwidget/resources/js/keywordwidget.js
To get access to the widget-config for i18n-strings, we need to add a template factory with the widget as a parameter.
This PR will fix an issue with the default result template.
> Add context-aware template factory to get access to the widget itself in templates

- docs/HISTORY.txt
- ftw/keywordwidget/widget.py
This PR fixes the term-lookup issue. See #27 for more information about the issue itself.
Unfortunately I couldn't reproduce this issue with tests. See the separate branch (https://github.com/4teamwork/ftw.keywordwidget/compare/es-27-fix-term-lookup-with-failing-tests?expand=1).
But I can reproduce it through the web.
Closes #27
> Fix an issue where the term-lookup will fail after the form-validation.

- docs/HISTORY.txt
- ftw/keywordwidget/field.py
- ftw/keywordwidget/widget.py
Unpersist the `allow_new` value on `ChoicePlus` fields.
Tests on `opengever.core` pass against this branch:
https://github.com/4teamwork/opengever.core/blob/94f12e1a49ffca784c7882468f33443f41ee43b0/sources.cfg
https://ci.4teamwork.ch/builds/129773
Should also invalidate https://github.com/4teamwork/ftw.keywordwidget/pull/30 as unnecessary.
Also provides an upgrade step to delete it from existing objects.
> Move the allow_new logic of ChoicePlus from the object to the request

- docs/HISTORY.txt
- ftw/keywordwidget/field.py
Seems what we want to do here is the validation from bootstrapfields `Field`.
https://github.com/zopefoundation/zope.schema/blob/4.2.2/src/zope/schema/_field.py#L376-L389
https://github.com/zopefoundation/zope.schema/blob/4.2.2/src/zope/schema/_bootstrapfields.py#L207-L212
Nothing failed in either `ftw.keywordwidget` or `opengever.core` when just removing the check, but I'm more comfortable just using copying the grandparent checks in manually here.
Closes https://github.com/4teamwork/ftw.keywordwidget/issues/32
> Remove improper 'parent of parent' field validations from the ChoicePlus field

- docs/HISTORY.txt
- ftw/keywordwidget/locales/fr/LC_MESSAGES/ftw.keywordwidget.po
There was a missing space after `Veuillez saisir` in the french translation.
> Fix french translations.

- docs/HISTORY.txt
- ftw/keywordwidget/widget.py
This PR fixes an issue where it was no longer possible to add tags on a keywordwidget, after using another async keywordwidget.
The main-problem is, that using an async widget will trigger all the widgets `update` method. This request seems to be correct, but in some cases, the user will be `Anonymous`.
The following check https://github.com/4teamwork/ftw.keywordwidget/blob/master/ftw/keywordwidget/widget.py#L156 will fail for the `ChoicePlus` and the `allow_new` attribute will be set to `False`. This value is persisted for the next requests.
So if we reload the page, the `allow_new` value is still `False`. Because the `js-config` will be updated before this security-check, we'll loose the permission to add new tags for this second request. Reloading once again will fix it again.
This PR …
> Fix an error where it was no longer possible to add tags after another async widget have been used.

- docs/HISTORY.txt
- ftw/keywordwidget/behavior.py
- ftw/keywordwidget/tests/test_different_cases.py
- ftw/keywordwidget/utils.py
- ftw/keywordwidget/vocabularies.py
- ftw/keywordwidget/widget.py
Adding new terms in the `KeywordWidget` in `async` mode was not allowed. All that is needed to add this feature is that newly added terms pass form validation so that the new values get set on the field (in the case of keywords, this will then update the `subject` index when the object is reindexed).
Because the `KeywordSearchableSource` uses a `SimpleVocabulary` in its implementation (`self.vocab`), we could simply have added the new terms in there, but this would have been a specific solution for the `KeywordSearchableSource`. Instead, we write a wrapper class `KeywordWidgetAddableSourceWrapper` that should allow to make any source addable in async mode. `KeywordWidgetAddableSourceWrapper` basically adds a `SimpleVocabulary` to the source instance to track newly added terms (the wrapper …
> Allow adding new terms in async mode.

- docs/HISTORY.txt
- ftw/keywordwidget/compat.py
- ftw/keywordwidget/vocabularies.py
- setup.py
When building catalog based vocabularies, we've had some race conditions where the catalog contents weren't up-to-date, because `collective.indexing` didn't process the required `reindexObject` calls yet.
This is because `collective.indexing` only patches `ZCatalog.searchResults()`, but not lower-level methods like `uniqueValuesFor()` or direct access to indexes. Therefore it also doesn't do the force-flush it usually does before querying the catalog. That way, you can, depending of execution order of events, end up with situations where newly added keywords have been "indexed", but the indexing hasn't yet been processed when the vocabularies are built.
We therefore explicitly flush the `collective.indexing` queue before accessing the catalog in these vocabularies.
> Fix race condition: Explicitly flush collective.indexing queue before building vocabularies

- ftw/keywordwidget/tests/__init__.py
- ftw/keywordwidget/tests/test_uninstall.py
- setup.py
We are no longer using `unittest2`, but `unittest`.
> Remove unittest2 dependency.
